---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: web
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring:latest
          envFrom:
            - secretRef:
                name: database-secret  
          resources:          
            limits:
              cpu: "250m"
              memory: "1Gi"
      imagePullSecrets:
      - name: docker-registry
              
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: web
  labels:
    app: backend
  annotations:
    service.beta.kubernetes.io/ncloud-load-balancer-layer-type: "nplb"
    service.beta.kubernetes.io/ncloud-load-balancer-internal: "false"
    service.beta.kubernetes.io/ncloud-load-balancer-size: "SMALL"
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer