apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: 5844b7c69326e570b585a575da59ab1d22de982b
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
