apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: f055d0b4ec1c349a19ece2bfb37373c175cbb0dd
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
