apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: fcf41e5847bce064b878f121b2d8dd25f91755ad
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
