apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: 8d4d11f58e70d9ff2673ad974c430cd3dfab9591
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
