apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: 8839390b4d84214bf88e61e8ae1e0d3c4085de20
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
