apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: 14cc107d8439bc4660c39b6f2824afe803e8beb9
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
