apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: c6ad56165d55bfc5c9f9d039c983d19443156d29
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
