apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: a4672fd49047c193a38b6a7b95928388978d839e
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
