apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: 5211be009cd816d2bbf7697a5b4816c89bd6f294
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
