apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring:309b762cdea9d841ed01e5782d1901bca6cc0e89
