apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: c11345290ce212ebe8244c995f0442a018e823f4
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
