apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: 034364cac21bbb37737426f0e163aa1c2f9dd97e
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
