apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: 9e28039c7ea4fa2a80ae2548b5b650131408ba76
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
