apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: 2c7abdf4f8b8439ef2e520e790c6c7aca54a5441
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
