apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: 255f180256b6f922ee9ad3d8a4812a5a632534c2
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
