apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: b40abbaf1f2ec4592ccbae2abda3999197e2eb21
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
