apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: 974d3e8d19e512adebdc6ef64dec7daefc63cc23
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
