apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: 1f117e2b3a75941919f0cbad625a473fdf8f94b9
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
