apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: web
images:
- name: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newName: jotunlmn.kr.private-ncr.ntruss.com/docker-pnu-bookstore-spring
  newTag: afe15bb864980e36e18930b93b20ca520c7dc6ce
resources:
- backend.yml
- backend_ingress.yml
- backend_hpa.yml
